#pragma once

#include "Settings.hpp"

enum class GameEvent
{
	// Game events
	START_GAME,
	END_GAME,
	START_TURN,
	END_TURN,
	// Player events
	PLAYER_DRAW,
	PLAYER_PLAY,
	PLAYER_PASS,
	PLAYER_END_TURN,
	PLAYER_END_GAME,
	// AI events
	AI_DRAW,
	AI_PLAY,
	AI_PASS,
	AI_END_TURN,
	AI_END_GAME,
	// Player conditions
	PLAYER_HAS_NO_CARDS,
	PLAYER_LIFE_CHANGED,
	// AI conditions
	AI_HAS_NO_CARDS,
	AI_LIFE_CHANGED,
	// Card events
	CARD_PLAYED,
	CARD_ATTACKED,
	CARD_DAMAGED,
	CARD_DESTROYED,
	CARD_STATUS_APPLIED,
	CARD_STATUS_REMOVED,
	CARD_EFFECT_TRIGGERED,
	// Board-specific events
	BOARD_RESET,
	UNIT_SUMMONED,
	SPELL_CAST,
	ITEM_USED,
	// Game state events
	MANA_REGEN,
	DECK_SHUFFLE,
	DECK_SORT,
	COUNTER_SPELL
};